---
- name: generate and copy ssh key
  hosts: localhost
  connection: local
  tags: ssh
  vars:
    - pub_key: ~/.ssh/id_rsa.pub
    - priv_key: ~/.ssh/id_rsa
  tasks:
  - name: generate sshkey
    command: ssh-keygen -t rsa -f {{priv_key}} -N "" -q
    args:
        creates: "{{ pub_key }}"
    tags: ssh

- name: copy ssh key
  hosts: acp
  su_user: fldengr
  remote_user: fldengr
  tags: ssh
  vars:
    - pub_key: ~/.ssh/id_rsa.pub

  tasks:
# authorized_key:manage_dir=yes is needed to ensure .ssh dir is created with correct permissions
  - name: copy sshkey
    authorized_key: user=fldengr
                    key="{{ lookup('file', pub_key) }}"
                    state=present
                    manage_dir=yes
    tags: ssh
