#!/bin/bash
####################################################################################
#Copyright 2014 ARRIS Enterprises, Inc. All rights reserved.
#This program is confidential and proprietary to ARRIS Enterprises, Inc. (ARRIS),
#and may not be copied, reproduced, modified, disclosed to others, published or used,
#in whole or in part, without the express prior written permission of ARRIS.
####################################################################################

while :
do
  runStatus=`sudo docker ps | grep registry`
  runSuccess=$?
  if [ "${runSuccess}" -gt 0 ] ;then
      sudo /home/docker/startDockerRegistry-2.1
  fi
  sleep 60
done
